# Generated by Django 3.1.7 on 2021-03-26 15:45

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, null=True, verbose_name='タイトル')),
                ('text', models.TextField(blank=True, null=True, verbose_name='説明')),
                ('posted_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日時')),
                ('likes', models.IntegerField(default=0, verbose_name='いいね')),
                ('status', models.CharField(choices=[('private', '非公開'), ('public', '公開')], default='public', max_length=7, verbose_name='公開設定')),
            ],
            options={
                'verbose_name': '投稿',
                'verbose_name_plural': '投稿リスト',
            },
        ),
    ]
