# Generated by Django 3.2 on 2021-04-15 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20210415_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='has_child',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='has_parent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.category', verbose_name='親カテゴリー'),
        ),
    ]
