# Generated by Django 3.2 on 2021-04-15 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20210416_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='has_child',
        ),
        migrations.RemoveField(
            model_name='category',
            name='has_parent',
        ),
        migrations.AddField(
            model_name='category',
            name='child_category',
            field=models.ManyToManyField(blank=True, related_name='_posts_category_child_category_+', to='posts.Category', verbose_name='子カテゴリー'),
        ),
    ]
