# Generated by Django 3.2 on 2021-04-15 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20210416_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='child_category',
        ),
    ]
