# Generated by Django 3.2 on 2021-04-19 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='写真撮影場所郵便番号'),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='写真撮影場所住所'),
        ),
    ]
