# Generated by Django 3.2 on 2021-04-19 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20210420_0207'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='prefecture',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='撮影した都道府県'),
        ),
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='撮影住所'),
        ),
        migrations.AlterField(
            model_name='post',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='撮影場所郵便番号'),
        ),
    ]
