# Generated by Django 3.2 on 2021-04-20 15:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20210420_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(null=True, upload_to='posts/', validators=[django.core.validators.FileExtensionValidator(['jpeg', 'jpg'])], verbose_name='画像'),
        ),
    ]
