# Generated by Django 3.1.7 on 2021-04-03 14:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_users',
            field=models.ManyToManyField(blank=True, related_name='_customuser_favorite_users_+', to=settings.AUTH_USER_MODEL, verbose_name='お気に入りのユーザー'),
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='custom_user',
        ),
    ]
