# Generated by Django 3.1.7 on 2021-04-06 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210403_2330'),
        ('users', '0002_auto_20210403_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='my_posts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_posts', to='posts.post', verbose_name='自分の投稿'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='favorite_posts',
            field=models.ManyToManyField(blank=True, related_name='users_favorite_posts', to='posts.Post', verbose_name='お気に入りの投稿'),
        ),
    ]
