# Generated by Django 3.2 on 2021-04-20 16:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_my_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='user_icons/', validators=[django.core.validators.FileExtensionValidator(['jpeg', 'jpg'])], verbose_name='ユーザーアイコン'),
        ),
    ]
