# Generated by Django 3.2 on 2021-04-27 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210428_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='favorite_users',
        ),
    ]
