# Generated by Django 3.2 on 2021-04-27 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_self_introduction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='self_introduction',
            new_name='selfintroduction',
        ),
    ]
