# Generated by Django 3.2 on 2021-04-27 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_self_introduction_customuser_selfintroduction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='selfintroduction',
            new_name='self_introduction',
        ),
    ]
